swagger: '2.0'
info:
  version: 1.0.0
  title: "API Supervisor"
basePath: "/c3p"
schemes:
  - https
paths:
  "/v1/Portal/Supervisor":
    post:
      tags:
      - "Supervisor"
      operationId: postSupervisor
      summary: Crea un Supervisor
      description: Crea un Supervisor
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-RqUID
          description: Identificador único del mensaje.
          in: header
          required: true
          type: string
          maxLength: 36
          minLength: 1
        - name: ReqPostSupervisor
          in: body
          required: true
          schema:
            $ref: '#/definitions/ReqPostSupervisor'
      responses:
        '201':
          description: creado
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
        '206':
          description: Error en la transacción
          schema:
            $ref: '#/definitions/Error'
          headers:
            X-RqUID:
              type: string
              description:  Identificador único del mensaje.
  "/v1/Portal/Supervisor/{Codigo}":
    get:
      tags:
      - "Supervisor"
      operationId: getSupervisor
      summary: Consultar un Supervisor
      description: Consultar un Supervisor
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-RqUID
          description: Identificador único del mensaje.
          in: header
          required: true
          type: string
          maxLength: 36
          minLength: 1
        - name: Codigo
          description: Identificador único del mensaje.
          in: path
          required: true
          type: string
      responses:
        '200':
          description: exitoso
          schema:
            $ref: '#/definitions/RespGetSupervisor'
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
        '206':
          description: Error en la transacción
          schema:
            $ref: '#/definitions/Error'
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
  "/v1/Portal/Supervisor/Autenticacion":
    post:
      tags:
      - "Supervisor"
      summary: Autentica un Supervisor
      description: Autentica un Supervisor
      operationId: postAutenticacion
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-RqUID
          description: Identificador único del mensaje.
          in: header
          required: true
          type: string
          maxLength: 36
          minLength: 1
        - name: ReqPostAutenticacion
          in: body
          required: true
          schema:
            $ref: '#/definitions/ReqPostAutenticacion'
      responses:
        '204':
          description: exitoso
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
        '206':
          description: Error en la transacción
          schema:
            $ref: '#/definitions/Error'
          headers:
            X-RqUID:
              type: string
              description: Identificador único del mensaje.
definitions:
  ReqPostSupervisor:
    type: object
    properties:
      Codigo:
        type: string
      Nombre:
        type: string
      Identificacion:
        type: string
      Correo:
        type: string
      Telefono:
        type: string
      Usuario:
        type: string
      Clave:
        type: string
  RespGetSupervisor:
    type: object
    properties:
      Codigo:
        type: string
      Nombre:
        type: string
      Identificacion:
        type: string
      Correo:
        type: string
      Telefono:
        type: string
      Usuario:
        type: string
  ReqPostAutenticacion:
    type: object
    properties:
      Usuario:
        type: string
      Clave:
        type: string
  Error:
    type: object
    properties:
      Codigo:
        type: string
      Mensaje:
        type: string
